dataset:
  folder_location : datasets/pcd_files/
  pcd:
    file_name       : Div02k_02 #file_name       : Div02k_02
    file_type       : .pcd

output:
  debug : True
  folder_location : 
    root    : '/output'
    topView : 'topView'
    sideView: 'sideView'
    pcd     : 'pointcloud'
    diam    : 'diam'
    debug   : 'debug'

yolov5:
  yolov5_pth: "yolov5"
  topView:
    axis      : "z"
    imgSize   : [320, 320]
    model_pth : "model_weights/topDetec640.pt"
    stepsize  : 0.05
  sideView:
    axis    : "x"
    imgSize : [320, 768]
    model_pth : "model_weights/v12_side.pt"
    stepsize : 0.02
    minNoPoints : 1500
    imgSizeTall : [320, 1280]
    width_tree : 0.2

yolov7:
  model_pth : "model_weights/seg_CrownTrunkv3.pt"
  imgShape : [640,640]

save_checks:
  min_tree_pts : 1500
  min_distance : 0.5